import { MigrationInterface, QueryRunner } from "typeorm";

export class InitDatabase1751090543680 implements MigrationInterface {
    name = 'InitDatabase1751090543680'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "category" ("category_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category_name" character varying(100), "description" text, "is_active" boolean DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cc7f32b7ab33c70b9e715afae84" PRIMARY KEY ("category_id"))`);
        await queryRunner.query(`CREATE TABLE "address" ("address_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "address_detail" character varying(500), "latitude" numeric(9,6), "longitude" numeric(9,6), "is_default" boolean DEFAULT false, "is_active" boolean DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "PK_db4aae0a059fd4ef7709cb802b0" PRIMARY KEY ("address_id"))`);
        await queryRunner.query(`CREATE TABLE "treatment_plan" ("treatment_plan_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "day_number" integer, "treatment_instruction" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "consultation_id" uuid, "product_id" uuid, CONSTRAINT "PK_57adb85a1d7be0ee4ddcc29bdff" PRIMARY KEY ("treatment_plan_id"))`);
        await queryRunner.query(`CREATE TABLE "ai_consultation" ("consultation_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "crop_type" character varying(100), "symptom_description" text, "growth_stage" character varying(50), "recommended_treatment" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "PK_f06fa8f353be07a09883edf1437" PRIMARY KEY ("consultation_id"))`);
        await queryRunner.query(`CREATE TABLE "invenstory" ("invenstory_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "business_license" character varying(255) NOT NULL, "invenstory_address" character varying(255) NOT NULL, "invenstory_lat" numeric(9,6), "invenstory_lng" numeric(9,6), "invenstory_img" character varying(255), "distributor_id" uuid, CONSTRAINT "REL_fb0d44f6817f37d34e0961000d" UNIQUE ("distributor_id"), CONSTRAINT "PK_831255ec4ef71ed06adbe15fa43" PRIMARY KEY ("invenstory_id"))`);
        await queryRunner.query(`CREATE TABLE "order_status" ("status_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_name" character varying(50), "description" text, "is_active" boolean DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d58a31b1f29e7726599cde0b1c2" PRIMARY KEY ("status_id"))`);
        await queryRunner.query(`CREATE TABLE "payment_method" ("payment_method_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "method_name" character varying(50), "description" text, "is_active" boolean DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ed16884cd19aa06b5eafbf0e013" PRIMARY KEY ("payment_method_id"))`);
        await queryRunner.query(`CREATE TABLE "order" ("order_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "total_amount" numeric(10,2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, "distributor_id" uuid, "status_id" uuid, "payment_method_id" uuid, CONSTRAINT "PK_58998c5eaeaacdd004dec8b5d86" PRIMARY KEY ("order_id"))`);
        await queryRunner.query(`CREATE TABLE "order_detail" ("order_detail_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" integer, "unit_price" numeric(10,2), "subtotal" numeric(10,2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "order_id" uuid, "batch_id" uuid, CONSTRAINT "PK_0a87692ed520d28d56e2ab425b7" PRIMARY KEY ("order_detail_id"))`);
        await queryRunner.query(`CREATE TABLE "product_type" ("product_type_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type_name" character varying(50), "description" text, "is_active" boolean DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a8166865294b0995e04f7fd7e12" PRIMARY KEY ("product_type_id"))`);
        await queryRunner.query(`CREATE TABLE "promotion" ("promotion_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "promotion_name" character varying(100), "description" text, "discount_value" numeric(10,2), "start_date" TIMESTAMP, "end_date" TIMESTAMP, "is_active" boolean DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "distributor_id" uuid, CONSTRAINT "PK_1227013bca6804cf7c972526721" PRIMARY KEY ("promotion_id"))`);
        await queryRunner.query(`CREATE TABLE "batch_product" ("batch_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "batch_number" character varying(50) NOT NULL, "quantity" integer, "manufactured_date" date, "expiry_date" date, "low_stock_threshold" integer DEFAULT '10', "is_active" boolean DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "product_id" uuid, "invenstory_id" uuid, CONSTRAINT "UQ_00282182dc332b5202e0454a121" UNIQUE ("batch_number"), CONSTRAINT "PK_9783ad350db6a237292093bad9e" PRIMARY KEY ("batch_id"))`);
        await queryRunner.query(`CREATE TABLE "cart_item" ("cart_item_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" integer, "unit_price" numeric(10,2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "cart_id" uuid, "batch_id" uuid, CONSTRAINT "PK_a96f2f9a014485fe47477c26c4a" PRIMARY KEY ("cart_item_id"))`);
        await queryRunner.query(`CREATE TABLE "cart" ("cart_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "PK_c741cd2adcfb2f2d1c2743d76b6" PRIMARY KEY ("cart_id"))`);
        await queryRunner.query(`CREATE TABLE "review" ("review_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rating" integer, "comment" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "product_id" uuid, "user_id" uuid, "distributor_id" uuid, "parent_review_id" uuid, CONSTRAINT "REL_42f559b5675aaf6deaa62a08bc" UNIQUE ("parent_review_id"), CONSTRAINT "PK_0106a233019ba9f4ee80aca2958" PRIMARY KEY ("review_id"))`);
        await queryRunner.query(`CREATE TABLE "role" ("role_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role_name" character varying(50), "description" text, "is_active" boolean DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_df46160e6aa79943b83c81e496e" PRIMARY KEY ("role_id"))`);
        await queryRunner.query(`CREATE TABLE "store_owner_request" ("store_owner_request_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "request_date" TIMESTAMP NOT NULL DEFAULT now(), "request_status" boolean NOT NULL DEFAULT false, "approved_date" TIMESTAMP, "name" character varying(255) NOT NULL, "business_license" character varying(255) NOT NULL, "invenstory_address" character varying(255) NOT NULL, "invenstory_lat" numeric(9,6), "invenstory_lng" numeric(9,6), "invenstory_img" character varying(255), "user_id" uuid, CONSTRAINT "REL_2dc0ed4b4f3de021c88d95c130" UNIQUE ("user_id"), CONSTRAINT "PK_74993a0d4321ed7f580a437a7f4" PRIMARY KEY ("store_owner_request_id"))`);
        await queryRunner.query(`CREATE TABLE "token" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "access_token" character varying(500), "access_token_expires_at" TIMESTAMP, "refresh_token" character varying(500), "refresh_token_expires_at" TIMESTAMP, "user_id" uuid, CONSTRAINT "PK_82fae97f905930df5d62a702fc9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d5b9f4694521b7fbb121aff385" ON "token" ("access_token") `);
        await queryRunner.query(`CREATE INDEX "IDX_b95cd28e9bf58b05f50e4ff909" ON "token" ("refresh_token") `);
        await queryRunner.query(`CREATE TABLE "voucher" ("voucher_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "voucher_code" character varying(50) NOT NULL, "min_order_value" numeric(10,2), "max_discount_value" numeric(10,2), "usage_limit" integer, "used_count" integer DEFAULT '0', "start_date" TIMESTAMP, "end_date" TIMESTAMP, "is_active" boolean DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "promotion_id" uuid, "distributorUserId" uuid, CONSTRAINT "UQ_88fa6913fd5006e11a183b38b40" UNIQUE ("voucher_code"), CONSTRAINT "PK_b885ed14e32391234a3bad969d2" PRIMARY KEY ("voucher_id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("user_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying(50) NOT NULL, "email" character varying(100) NOT NULL, "password" character varying(255) NOT NULL, "full_name" character varying(255), "phone_number" character varying(20), "avatar" character varying(255), "cccd" character varying(12), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "role_id" uuid NOT NULL, CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb" UNIQUE ("username"), CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_758b8ce7c18b9d347461b30228d" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_758b8ce7c18b9d347461b30228" ON "user" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_78a916df40e02a9deb1c4b75ed" ON "user" ("username") `);
        await queryRunner.query(`CREATE INDEX "IDX_e12875dfb3b1d92d7d7c5377e2" ON "user" ("email") `);
        await queryRunner.query(`CREATE TABLE "disease" ("disease_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "disease_name" character varying(100), "description" text, "is_active" boolean DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_43c8ddf9bbd685cb44ea7159be5" PRIMARY KEY ("disease_id"))`);
        await queryRunner.query(`CREATE TABLE "ingredient_disease" ("ingredient_id" uuid NOT NULL, "disease_id" uuid NOT NULL, "effectiveness_description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_820b3429edcbac23d1edf79aad0" PRIMARY KEY ("ingredient_id", "disease_id"))`);
        await queryRunner.query(`CREATE TABLE "active_ingredient" ("ingredient_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ingredient_name" character varying(100), "description" text, "hazard_level" character varying(50), "is_active" boolean DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0210580ea4202b49a90513b89bb" PRIMARY KEY ("ingredient_id"))`);
        await queryRunner.query(`CREATE TABLE "product_ingredient" ("product_id" uuid NOT NULL, "ingredient_id" uuid NOT NULL, "concentration" numeric(5,2), "is_primary" boolean DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f67be6dcd1883f638cba90662ca" PRIMARY KEY ("product_id", "ingredient_id"))`);
        await queryRunner.query(`CREATE TABLE "product" ("product_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_name" character varying(100), "description" text, "usage_instructions" text, "is_active" boolean DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "distributor_id" uuid, CONSTRAINT "PK_1de6a4421ff0c410d75af27aeee" PRIMARY KEY ("product_id"))`);
        await queryRunner.query(`CREATE TABLE "wishlist" ("wishlist_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, "product_id" uuid, CONSTRAINT "REL_512bf776587ad5fc4f804277d7" UNIQUE ("user_id"), CONSTRAINT "PK_bf0b54a57200f8116d7366bf42c" PRIMARY KEY ("wishlist_id"))`);
        await queryRunner.query(`CREATE TABLE "product_image" ("product_image_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "image_url" character varying(255) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "product_id" uuid, CONSTRAINT "PK_c0532fda47499dffa32b81e4d90" PRIMARY KEY ("product_image_id"))`);
        await queryRunner.query(`CREATE TABLE "batch_product_type" ("productTypeProductTypeId" uuid NOT NULL, "batchProductBatchId" uuid NOT NULL, CONSTRAINT "PK_feaad865de6a6caabb0dde75389" PRIMARY KEY ("productTypeProductTypeId", "batchProductBatchId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_76f2d4dca3dd0acd0e449816f1" ON "batch_product_type" ("productTypeProductTypeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec0cdb4e7008871657e2069980" ON "batch_product_type" ("batchProductBatchId") `);
        await queryRunner.query(`CREATE TABLE "batch_promotion" ("batchProductBatchId" uuid NOT NULL, "promotionPromotionId" uuid NOT NULL, CONSTRAINT "PK_97d48e6a65504f646f7ea1bf222" PRIMARY KEY ("batchProductBatchId", "promotionPromotionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_32bb1bc7499dc25c6e81058f83" ON "batch_promotion" ("batchProductBatchId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0812dff98cbeaaf59429e6be3" ON "batch_promotion" ("promotionPromotionId") `);
        await queryRunner.query(`CREATE TABLE "user_voucher" ("userUserId" uuid NOT NULL, "voucherVoucherId" uuid NOT NULL, CONSTRAINT "PK_31a10063a17041abf3e7843af3e" PRIMARY KEY ("userUserId", "voucherVoucherId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c078aab6dfc0297aa5365fbb6b" ON "user_voucher" ("userUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_18a1e7e4d2951e76ee047c2621" ON "user_voucher" ("voucherVoucherId") `);
        await queryRunner.query(`CREATE TABLE "product_category" ("productProductId" uuid NOT NULL, "categoryCategoryId" uuid NOT NULL, CONSTRAINT "PK_4c73a1c2d5d2112cf08b1f1038c" PRIMARY KEY ("productProductId", "categoryCategoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8d3fb31ab54261ff8755eebc3e" ON "product_category" ("productProductId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4b7c62655ed69ca4bf462a4f02" ON "product_category" ("categoryCategoryId") `);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "FK_35cd6c3fafec0bb5d072e24ea20" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_plan" ADD CONSTRAINT "FK_2abc33dbc5cb40142c50005781d" FOREIGN KEY ("consultation_id") REFERENCES "ai_consultation"("consultation_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_plan" ADD CONSTRAINT "FK_3033471e08f961bc0e342d877a8" FOREIGN KEY ("product_id") REFERENCES "product"("product_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_consultation" ADD CONSTRAINT "FK_ff3764a63bb1925739564d3e078" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invenstory" ADD CONSTRAINT "FK_fb0d44f6817f37d34e0961000d0" FOREIGN KEY ("distributor_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_199e32a02ddc0f47cd93181d8fd" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_df56039592a4bbbd3fa4a19f141" FOREIGN KEY ("distributor_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_8ea75b2a26f83f3bc98b9c6aaf6" FOREIGN KEY ("status_id") REFERENCES "order_status"("status_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_451b11cb12bc07db00d19c5a511" FOREIGN KEY ("payment_method_id") REFERENCES "payment_method"("payment_method_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_detail" ADD CONSTRAINT "FK_a6ac5c99b8c02bd4ee53d3785be" FOREIGN KEY ("order_id") REFERENCES "order"("order_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_detail" ADD CONSTRAINT "FK_71047f435ef0dc34a2f4dff7c91" FOREIGN KEY ("batch_id") REFERENCES "batch_product"("batch_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promotion" ADD CONSTRAINT "FK_c8ec9d8b659b2d5e48c9205bde5" FOREIGN KEY ("distributor_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch_product" ADD CONSTRAINT "FK_fe8ffd5885026f19ba3bbf4d254" FOREIGN KEY ("product_id") REFERENCES "product"("product_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch_product" ADD CONSTRAINT "FK_d12f4b1c62c862e86fa7d26f9b7" FOREIGN KEY ("invenstory_id") REFERENCES "invenstory"("invenstory_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_item" ADD CONSTRAINT "FK_b6b2a4f1f533d89d218e70db941" FOREIGN KEY ("cart_id") REFERENCES "cart"("cart_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_item" ADD CONSTRAINT "FK_133f100e56d9b2a562f16ff7208" FOREIGN KEY ("batch_id") REFERENCES "batch_product"("batch_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart" ADD CONSTRAINT "FK_f091e86a234693a49084b4c2c86" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_26b533e15b5f2334c96339a1f08" FOREIGN KEY ("product_id") REFERENCES "product"("product_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_81446f2ee100305f42645d4d6c2" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_6d31943ee59e2a4b00f78b40836" FOREIGN KEY ("distributor_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_42f559b5675aaf6deaa62a08bc4" FOREIGN KEY ("parent_review_id") REFERENCES "review"("review_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_owner_request" ADD CONSTRAINT "FK_2dc0ed4b4f3de021c88d95c130e" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "token" ADD CONSTRAINT "FK_e50ca89d635960fda2ffeb17639" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "voucher" ADD CONSTRAINT "FK_022016a80c2d6013d396e340e93" FOREIGN KEY ("promotion_id") REFERENCES "promotion"("promotion_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "voucher" ADD CONSTRAINT "FK_1da5d93c7dacaff28a6e965e4c1" FOREIGN KEY ("distributorUserId") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_fb2e442d14add3cefbdf33c4561" FOREIGN KEY ("role_id") REFERENCES "role"("role_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient_disease" ADD CONSTRAINT "FK_9cdb632c14611a0352621283e41" FOREIGN KEY ("ingredient_id") REFERENCES "active_ingredient"("ingredient_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient_disease" ADD CONSTRAINT "FK_30fac8a30b4d05a1f26855b8a30" FOREIGN KEY ("disease_id") REFERENCES "disease"("disease_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_ingredient" ADD CONSTRAINT "FK_a7a4b2de441d2ab00df5b0d4cdd" FOREIGN KEY ("product_id") REFERENCES "product"("product_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_ingredient" ADD CONSTRAINT "FK_3f9b3e7181dc8cd771e6d513b7b" FOREIGN KEY ("ingredient_id") REFERENCES "active_ingredient"("ingredient_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_29624c341939d2f286f552a95bc" FOREIGN KEY ("distributor_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishlist" ADD CONSTRAINT "FK_512bf776587ad5fc4f804277d76" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishlist" ADD CONSTRAINT "FK_16f64e06715ce4fea8257cc42c5" FOREIGN KEY ("product_id") REFERENCES "product"("product_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_image" ADD CONSTRAINT "FK_dbc7d9aa7ed42c9141b968a9ed3" FOREIGN KEY ("product_id") REFERENCES "product"("product_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch_product_type" ADD CONSTRAINT "FK_76f2d4dca3dd0acd0e449816f1e" FOREIGN KEY ("productTypeProductTypeId") REFERENCES "product_type"("product_type_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "batch_product_type" ADD CONSTRAINT "FK_ec0cdb4e7008871657e20699804" FOREIGN KEY ("batchProductBatchId") REFERENCES "batch_product"("batch_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch_promotion" ADD CONSTRAINT "FK_32bb1bc7499dc25c6e81058f831" FOREIGN KEY ("batchProductBatchId") REFERENCES "batch_product"("batch_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "batch_promotion" ADD CONSTRAINT "FK_b0812dff98cbeaaf59429e6be3e" FOREIGN KEY ("promotionPromotionId") REFERENCES "promotion"("promotion_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_voucher" ADD CONSTRAINT "FK_c078aab6dfc0297aa5365fbb6bf" FOREIGN KEY ("userUserId") REFERENCES "user"("user_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_voucher" ADD CONSTRAINT "FK_18a1e7e4d2951e76ee047c2621a" FOREIGN KEY ("voucherVoucherId") REFERENCES "voucher"("voucher_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_category" ADD CONSTRAINT "FK_8d3fb31ab54261ff8755eebc3ef" FOREIGN KEY ("productProductId") REFERENCES "product"("product_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_category" ADD CONSTRAINT "FK_4b7c62655ed69ca4bf462a4f026" FOREIGN KEY ("categoryCategoryId") REFERENCES "category"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_category" DROP CONSTRAINT "FK_4b7c62655ed69ca4bf462a4f026"`);
        await queryRunner.query(`ALTER TABLE "product_category" DROP CONSTRAINT "FK_8d3fb31ab54261ff8755eebc3ef"`);
        await queryRunner.query(`ALTER TABLE "user_voucher" DROP CONSTRAINT "FK_18a1e7e4d2951e76ee047c2621a"`);
        await queryRunner.query(`ALTER TABLE "user_voucher" DROP CONSTRAINT "FK_c078aab6dfc0297aa5365fbb6bf"`);
        await queryRunner.query(`ALTER TABLE "batch_promotion" DROP CONSTRAINT "FK_b0812dff98cbeaaf59429e6be3e"`);
        await queryRunner.query(`ALTER TABLE "batch_promotion" DROP CONSTRAINT "FK_32bb1bc7499dc25c6e81058f831"`);
        await queryRunner.query(`ALTER TABLE "batch_product_type" DROP CONSTRAINT "FK_ec0cdb4e7008871657e20699804"`);
        await queryRunner.query(`ALTER TABLE "batch_product_type" DROP CONSTRAINT "FK_76f2d4dca3dd0acd0e449816f1e"`);
        await queryRunner.query(`ALTER TABLE "product_image" DROP CONSTRAINT "FK_dbc7d9aa7ed42c9141b968a9ed3"`);
        await queryRunner.query(`ALTER TABLE "wishlist" DROP CONSTRAINT "FK_16f64e06715ce4fea8257cc42c5"`);
        await queryRunner.query(`ALTER TABLE "wishlist" DROP CONSTRAINT "FK_512bf776587ad5fc4f804277d76"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_29624c341939d2f286f552a95bc"`);
        await queryRunner.query(`ALTER TABLE "product_ingredient" DROP CONSTRAINT "FK_3f9b3e7181dc8cd771e6d513b7b"`);
        await queryRunner.query(`ALTER TABLE "product_ingredient" DROP CONSTRAINT "FK_a7a4b2de441d2ab00df5b0d4cdd"`);
        await queryRunner.query(`ALTER TABLE "ingredient_disease" DROP CONSTRAINT "FK_30fac8a30b4d05a1f26855b8a30"`);
        await queryRunner.query(`ALTER TABLE "ingredient_disease" DROP CONSTRAINT "FK_9cdb632c14611a0352621283e41"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_fb2e442d14add3cefbdf33c4561"`);
        await queryRunner.query(`ALTER TABLE "voucher" DROP CONSTRAINT "FK_1da5d93c7dacaff28a6e965e4c1"`);
        await queryRunner.query(`ALTER TABLE "voucher" DROP CONSTRAINT "FK_022016a80c2d6013d396e340e93"`);
        await queryRunner.query(`ALTER TABLE "token" DROP CONSTRAINT "FK_e50ca89d635960fda2ffeb17639"`);
        await queryRunner.query(`ALTER TABLE "store_owner_request" DROP CONSTRAINT "FK_2dc0ed4b4f3de021c88d95c130e"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_42f559b5675aaf6deaa62a08bc4"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_6d31943ee59e2a4b00f78b40836"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_81446f2ee100305f42645d4d6c2"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_26b533e15b5f2334c96339a1f08"`);
        await queryRunner.query(`ALTER TABLE "cart" DROP CONSTRAINT "FK_f091e86a234693a49084b4c2c86"`);
        await queryRunner.query(`ALTER TABLE "cart_item" DROP CONSTRAINT "FK_133f100e56d9b2a562f16ff7208"`);
        await queryRunner.query(`ALTER TABLE "cart_item" DROP CONSTRAINT "FK_b6b2a4f1f533d89d218e70db941"`);
        await queryRunner.query(`ALTER TABLE "batch_product" DROP CONSTRAINT "FK_d12f4b1c62c862e86fa7d26f9b7"`);
        await queryRunner.query(`ALTER TABLE "batch_product" DROP CONSTRAINT "FK_fe8ffd5885026f19ba3bbf4d254"`);
        await queryRunner.query(`ALTER TABLE "promotion" DROP CONSTRAINT "FK_c8ec9d8b659b2d5e48c9205bde5"`);
        await queryRunner.query(`ALTER TABLE "order_detail" DROP CONSTRAINT "FK_71047f435ef0dc34a2f4dff7c91"`);
        await queryRunner.query(`ALTER TABLE "order_detail" DROP CONSTRAINT "FK_a6ac5c99b8c02bd4ee53d3785be"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_451b11cb12bc07db00d19c5a511"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_8ea75b2a26f83f3bc98b9c6aaf6"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_df56039592a4bbbd3fa4a19f141"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_199e32a02ddc0f47cd93181d8fd"`);
        await queryRunner.query(`ALTER TABLE "invenstory" DROP CONSTRAINT "FK_fb0d44f6817f37d34e0961000d0"`);
        await queryRunner.query(`ALTER TABLE "ai_consultation" DROP CONSTRAINT "FK_ff3764a63bb1925739564d3e078"`);
        await queryRunner.query(`ALTER TABLE "treatment_plan" DROP CONSTRAINT "FK_3033471e08f961bc0e342d877a8"`);
        await queryRunner.query(`ALTER TABLE "treatment_plan" DROP CONSTRAINT "FK_2abc33dbc5cb40142c50005781d"`);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "FK_35cd6c3fafec0bb5d072e24ea20"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b7c62655ed69ca4bf462a4f02"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d3fb31ab54261ff8755eebc3e"`);
        await queryRunner.query(`DROP TABLE "product_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18a1e7e4d2951e76ee047c2621"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c078aab6dfc0297aa5365fbb6b"`);
        await queryRunner.query(`DROP TABLE "user_voucher"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0812dff98cbeaaf59429e6be3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32bb1bc7499dc25c6e81058f83"`);
        await queryRunner.query(`DROP TABLE "batch_promotion"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec0cdb4e7008871657e2069980"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76f2d4dca3dd0acd0e449816f1"`);
        await queryRunner.query(`DROP TABLE "batch_product_type"`);
        await queryRunner.query(`DROP TABLE "product_image"`);
        await queryRunner.query(`DROP TABLE "wishlist"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`DROP TABLE "product_ingredient"`);
        await queryRunner.query(`DROP TABLE "active_ingredient"`);
        await queryRunner.query(`DROP TABLE "ingredient_disease"`);
        await queryRunner.query(`DROP TABLE "disease"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e12875dfb3b1d92d7d7c5377e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78a916df40e02a9deb1c4b75ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_758b8ce7c18b9d347461b30228"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "voucher"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b95cd28e9bf58b05f50e4ff909"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5b9f4694521b7fbb121aff385"`);
        await queryRunner.query(`DROP TABLE "token"`);
        await queryRunner.query(`DROP TABLE "store_owner_request"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP TABLE "review"`);
        await queryRunner.query(`DROP TABLE "cart"`);
        await queryRunner.query(`DROP TABLE "cart_item"`);
        await queryRunner.query(`DROP TABLE "batch_product"`);
        await queryRunner.query(`DROP TABLE "promotion"`);
        await queryRunner.query(`DROP TABLE "product_type"`);
        await queryRunner.query(`DROP TABLE "order_detail"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`DROP TABLE "payment_method"`);
        await queryRunner.query(`DROP TABLE "order_status"`);
        await queryRunner.query(`DROP TABLE "invenstory"`);
        await queryRunner.query(`DROP TABLE "ai_consultation"`);
        await queryRunner.query(`DROP TABLE "treatment_plan"`);
        await queryRunner.query(`DROP TABLE "address"`);
        await queryRunner.query(`DROP TABLE "category"`);
    }

}
